-- Tokyo Club CMS — seed data
-- Run after supabase/schema.sql to populate initial content.
-- Safe to re-run (upserts by primary key).

-- ---------------------------------------------------------------------------
-- Pages (home / menu / experience / gallery / contact / settings)
-- ---------------------------------------------------------------------------
insert into public.pages (key, content, updated_at) values
  ('home',       '{"seo":{"title":"Tokyo Sushi Speakeasy | Modern Japanese Speakeasy in South Beach","description":"A hidden Japanese speakeasy in South Beach serving premium sushi, craft cocktails, and late-night energy at 1000 Collins Ave. Book your table."},"hero":{"eyebrow":"Japanese speakeasy meets Miami nightlife","title":"South Beach''s late-night Sushi ritual.","description":"Premium sushi, sculpted cocktails, moody lighting, and a room built for date nights, celebrations, and unforgettable after-dark plans.","video":"/videos/Tokyo%20Video.MOV","poster":{"src":"/pictures/home-banner-bg.png","alt":"A cocktail and premium sushi dishes staged on a dramatic black table.","width":1920,"height":1080},"sideImage":{"src":"/pictures/04-lychee-orchid-and-citrus-cocktails.jpg","alt":"Signature cocktails with floral garnishes against a dark speakeasy backdrop.","width":2048,"height":1365},"primaryButtonLabel":"Book a Table","secondaryButton":{"label":"Explore the Menu","href":"/menu"},"marquee":["4.8 Google Rating","200+ Reviews","1000 Collins Ave","Wed-Mon 5PM-12AM"]},"experience":{"eyebrow":"The ultimate sushi speakeasy in South Beach","pillars":[{"title":"Japanese craft, Miami pulse","body":"Tokyo Sushi Speakeasy balances refined technique with a nightlife energy that feels unmistakably South Beach. Every plate is built with the precision of an Edomae kitchen — clean cuts, seasonal instinct, and a respect for simplicity — then served inside a room that moves to its own rhythm.","image":{"src":"/pictures/02-seared-tuna-tataki-with-microgreens.jpg","alt":"Seared tuna tataki plated with microgreens showcasing Japanese precision.","width":1365,"height":2048}},{"title":"Dinner becomes a scene","body":"Every table is staged with contrast, glow, and shareable moments designed for dates and celebrations. The room is low-lit, the plating is bold, and the energy builds as the night goes on.","image":{"src":"/pictures/11-beef-sushi-roll-with-cocktail-and-bao.jpg","alt":"Beef sushi roll served alongside a craft cocktail and bao buns.","width":1365,"height":2048}},{"title":"Late night, done right","body":"Open Wednesday through Monday until midnight, Tokyo Sushi Speakeasy is the after-dark destination South Beach deserves. Trusted by locals, celebrated by visitors, and rated 4.8 stars by our guests."}]}}'::jsonb, now()),
  ('menu',       '{"seo":{"title":"Sushi Menu | Tokyo Sushi Speakeasy","description":"Explore the Tokyo Sushi Speakeasy menu — nigiri, sashimi, signature rolls, craft cocktails, sake, and chef specials. South Beach''s finest Japanese dining."},"hero":{"eyebrow":"Tokyo Sushi Speakeasy","title":"The Menu","description":"Sushi precision, speakeasy cocktails, and late-night share plates — crafted for the full South Beach night.","image":{"src":"/pictures/05-japanese-dishes-spread-with-cocktail.jpg","alt":"A dramatic spread of Japanese dishes and cocktails at Tokyo Sushi Speakeasy.","width":1365,"height":2048},"primaryButtonLabel":"Book a Table"},"menuLinks":{"food":{"label":"Food Menu","href":"/menu/Tokyo-Sushi-Speakeasy-Menu-Food.png"},"drink":{"label":"Drink Menu","href":"/menu/Tokyo-Sushi-Speakeasy-Menu-Drink.png"}},"footnotes":["A 20% service charge and sales tax are added to your check.","*Consuming raw or undercooked meats, poultry, seafood, shellfish, or eggs may increase your risk of foodborne illness, especially if you have certain medical conditions."]}'::jsonb, now()),
  ('experience', '{"seo":{"title":"The Experience | Tokyo Sushi Speakeasy","description":"Step inside Tokyo Sushi Speakeasy — an intimate hidden bar in South Beach with moody lighting, Japanese craftsmanship, and unforgettable nightlife energy."},"hero":{"eyebrow":"Tokyo Sushi Speakeasy","title":"The Experience","description":"A modern Japanese speakeasy where culinary artistry, handcrafted cocktails, and unforgettable atmosphere converge in the heart of South Beach.","image":{"src":"/pictures/experience-banner-bg.png","alt":"A moody table setting inside Tokyo Sushi Speakeasy with Japanese scroll art and dark slatted walls.","width":1365,"height":2048},"primaryButtonLabel":"Reserve Your Night","secondaryButton":{"label":"Explore the Menu","href":"/menu"}},"sections":{"storyEyebrow":"Our story","storyTitle":"A hidden world behind the door.","storyBodyOne":"At Tokyo Sushi Speakeasy, we blend the artistry of traditional sushi craftsmanship with an elevated nightlife atmosphere, creating an experience that delights the senses and excites the palate. Our sushi masters meticulously select the finest, freshest ingredients — crafting every roll, sashimi, and nigiri to perfection.","storyBodyTwo":"Step inside and you''ll find a space that feels both intimate and alive — dark lacquer walls, warm golden light, and the kind of energy that turns a dinner reservation into a lasting memory.","storyImage":{"src":"/pictures/Experiance page.png","alt":"The intimate Tokyo Sushi Speakeasy dining room in warm, moody light.","width":1365,"height":2048},"proverb":"Hara hachibu-me ni isha irazu.","proverbTranslation":"If you fill your stomach to 8/10, you don''t need a doctor. — Japanese proverb","proverbImage":{"src":"/pictures/29-DSC08280.jpg","alt":"Golden koi fish sculptures swimming across a dark textured wall inside Tokyo Sushi Speakeasy.","width":1365,"height":2048},"featuresEyebrow":"What sets us apart","featuresTitle":"Experience Tokyo, one bite at a time.","features":[{"title":"Premium sushi","description":"Fresh nigiri, sashimi, and signature rolls crafted with precision by experienced sushi masters."},{"title":"Craft cocktails","description":"Floral, citrus-led, and smoky cocktails built for the speakeasy mood."},{"title":"Immersive atmosphere","description":"Moody lighting, dark wood finishes, and an intimate hidden-bar layout."},{"title":"Late-night dining","description":"Open late — serving premium sushi and cocktails until midnight, Wednesday through Monday."}]}}'::jsonb, now()),
  ('gallery',    '{"seo":{"title":"Gallery | Tokyo Sushi Speakeasy","description":"Browse the gallery of Tokyo Sushi Speakeasy — premium sushi, craft cocktails, and moody interior shots from our South Beach hidden bar."},"hero":{"eyebrow":"Gallery","title":"Every detail, worth the frame.","description":"","image":{"src":"/pictures/04-lychee-orchid-and-citrus-cocktails.jpg","alt":"Signature cocktails with floral garnishes against a dark speakeasy backdrop.","width":2048,"height":1365}},"cta":{"eyebrow":"The room looks even better in person.","title":"See it live in South Beach.","description":"","buttonLabel":"Reserve a Table"}}'::jsonb, now()),
  ('contact',    '{"seo":{"title":"Contact | Tokyo Sushi Speakeasy","description":"Get in touch with Tokyo Sushi Speakeasy. Reserve a table, plan a private event, or reach our team at 1000 Collins Ave, South Beach."},"hero":{"eyebrow":"Private events & celebrations","title":"The venue already feels like the event.","description":"Birthdays, date nights, group dinners — Tokyo Sushi Speakeasy is built for nights that turn into stories.","image":{"src":"/pictures/contact-us-bg.png","alt":"Moody table setting with cocktails and Japanese dishes at Tokyo Sushi Speakeasy","width":1365,"height":2048},"primaryButtonLabel":"Reserve a Table","secondaryButton":{"label":"Call to Plan","href":"tel:+17867289318"}},"occasions":[{"title":"Date Nights","description":"Low light, standout cocktails, and a menu built for lingering together."},{"title":"Birthdays","description":"Turn dinner into a celebration with dramatic plates, music, and bottle-worthy energy."},{"title":"Groups & Nights Out","description":"From visiting crews to after-dark plans, Tokyo Sushi Speakeasy sets the mood for the full evening."}],"formIntro":{"eyebrow":"Get in touch","title":"Send us a message","description":"Questions about reservations, events, or anything else — we''re here to help make your night happen."},"sidebar":{"visitEyebrow":"Visit us","callEyebrow":"Prefer to call?","callDescription":"For group bookings and same-day plans, calling is the fastest way to get everything sorted.","eventsEyebrow":"Large parties & private events","eventsDescription":"For groups of 15+ guests or private event inquiries, reach our events team directly.","eventsEmail":"events@fairwindhotelmiami.com","followEyebrow":"Follow along"}}'::jsonb, now()),
  ('settings',   '{"phoneNumber":"(786) 728-9318","emailAddress":"events@fairwindhotelmiami.com","address":"1000 Collins Ave, Miami Beach, FL 33139","reservationLink":"https://www.opentable.com/r/tokyo-club-reservations-miami-beach?restref=1480237&lang=en-US&ot_source=Restaurant%20website&ot_campaign=LP&utm_source=google&utm_medium=cpc&utm_campaign=tokyo_search","visitMenu":"Visit Us","phoneNumberMenu":"Call Us","addressMenu":"Find Us"}'::jsonb, now())
on conflict (key) do update set
  content    = excluded.content,
  updated_at = excluded.updated_at;

-- ---------------------------------------------------------------------------
-- Categories
-- ---------------------------------------------------------------------------
insert into public.categories (slug, name, updated_at) values
  ('sushi-culture',  'Sushi Culture',  now()),
  ('chef-stories',   'Chef Stories',   now()),
  ('events',         'Events',         now()),
  ('cocktails',      'Cocktails',      now()),
  ('south-beach',    'South Beach',    now()),
  ('experience',     'Experience',     now()),
  ('miami-nightlife','Miami Nightlife',now())
on conflict (slug) do update set
  name       = excluded.name,
  updated_at = excluded.updated_at;

